// * Nuxt 4 LTS config — Intersport Club IDF e-shop
// ? npx netlify-cli build && npx netlify-cli deploy --prod
export default defineNuxtConfig({
  compatibilityDate: '2025-07-15',
  devtools: { enabled: true },

  modules: [
    // * Tailwind v4 is pulled in by @nuxt/ui via @tailwindcss/vite —
    // * no separate tailwind module, theme is defined in assets/css/main.css.
    '@nuxtjs/supabase',
    '@nuxt/ui',
    '@pinia/nuxt',
    '@nuxtjs/i18n',
    '@vueuse/nuxt',
    '@nuxtjs/color-mode',
    // * SEO trio (no headless-browser deps, safe for `nuxt generate`).
    // * og:image is set to real URLs via useSeoMeta, so nuxt-og-image is omitted.
    '@nuxtjs/sitemap',
    '@nuxtjs/robots',
    'nuxt-schema-org',
  ],

  // * Single source of truth for canonical URL + site name, read by sitemap,
  // * robots and schema-org. nuxt-site-config also honours NUXT_PUBLIC_SITE_URL
  // * from the env, which OVERRIDES this — set that to the live domain at launch.
  site: {
    url: 'https://www.intersportclubidf.com',
    name: 'Intersport Club IDF',
    description:
      'Boutique en ligne Intersport Club IDF — équipements et textiles personnalisés pour les clubs sportifs d\'Île-de-France.',
  },

  // * robots.txt is generated by @nuxtjs/robots (the static public/robots.txt was
  // * removed). Back-office, checkout and order pages must never be indexed.
  robots: {
    disallow: ['/admin', '/checkout', '/order', '/confirm'],
  },

  sitemap: {
    // * Keep private/transient routes out of the sitemap.
    exclude: ['/admin/**', '/checkout', '/order/**', '/confirm'],
    // * Dynamic product URLs come from this server source (queries Supabase).
    sources: ['/api/__sitemap__/urls'],
  },

  // * Back-office is client-only. Admin pages mutate local refs inside
  // *   useAsyncData (loading/requests/eventLog/...) which Nuxt doesn't
  // *   serialize, so SSR vs hydration drift caused hydration mismatches and
  // *   stuck loading states. `ssr: false` in definePageMeta is NOT a real
  // *   Nuxt option — routeRules is. Storefront keeps SSR for SEO.
  routeRules: {
    '/admin/**': { ssr: false },
  },

  // * Nitro's dependency tracer drops `unhead/server` from the serverless
  // * bundle (it copies unhead/plugins + unhead/utils but not unhead/server),
  // * so SSR crashes with ERR_MODULE_NOT_FOUND: unhead/dist/server.mjs on
  // * Netlify. Inlining unhead into the server chunks sidesteps the trace gap.
  nitro: {
    externals: {
      inline: ['unhead'],
    },
  },

  css: ['~/assets/css/main.css'],

  supabase: {
    // * Keys read from env: NUXT_PUBLIC_SUPABASE_URL / NUXT_PUBLIC_SUPABASE_KEY
    // * (the module falls back to SUPABASE_URL / SUPABASE_KEY if those are unset).
    // * redirect: false — authentication gates are handled by our custom
    // * middlewares (admin.ts, backoffice.ts, auth.ts, customer-only.ts)
    // * because admin routes must redirect to /admin/login, not /login.
    redirect: false,
    redirectOptions: {
      login: '/login',
      callback: '/confirm',
      exclude: [
        '/',
        '/catalog',
        '/contact',
        '/login',
        '/register',
        '/admin/login',
        '/sport/*',
        '/club/*',
        '/product/*',
      ],
    },
  },

  i18n: {
    // * Nuxt 4 + @nuxtjs/i18n v10 default dir is i18n/locales/
    locales: [
      { code: 'fr', file: 'fr.json', name: 'Français' },
      { code: 'en', file: 'en.json', name: 'English' },
    ],
    defaultLocale: 'fr',
    // lazy: true,
    strategy: 'no_prefix',
    // * Auto-detect the browser language; fall back to French when the browser
    // * asks for anything that isn't in `locales`. User's manual toggle is
    // * remembered via the i18n_redirected cookie.
    detectBrowserLanguage: {
      useCookie: true,
      fallbackLocale: 'fr',
    },
  },

  colorMode: { classSuffix: '', preference: 'system', fallback: 'light' },

  app: {
    pageTransition: { name: 'page', mode: 'out-in' },
    layoutTransition: { name: 'layout', mode: 'out-in' },
    head: {
      title: 'Intersport Club IDF',
      link: [
        { rel: 'preconnect', href: 'https://fonts.googleapis.com' },
        { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' },
        {
          rel: 'stylesheet',
          href: 'https://fonts.googleapis.com/css2?family=Barlow:wght@400;500;600;700&family=Barlow+Condensed:wght@500;600;700;800&display=swap',
        },
      ],
    },
  },

  // * No server-only block: every secret (Brevo, Colissimo, SystemPay merchant
  // * credentials, service-role key) lives on the Supabase edge-function side
  // * and is read there via Deno.env. Nothing in app/ or server/ reads them.
  runtimeConfig: {
    public: {
      // * Exposed to client — only publishable values
      systempayEndpoint: process.env.NUXT_PUBLIC_SYSTEMPAY_ENDPOINT || '',
      systempayPublicKey: process.env.NUXT_PUBLIC_SYSTEMPAY_PUBLIC_KEY,
      siteUrl: process.env.NUXT_PUBLIC_SITE_URL || '',
      // ? Fallback for server/api/__sitemap__/urls.ts — @nuxtjs/supabase's own
      // ? public.supabase.{url,key} stays the primary source.
      supabaseUrl: process.env.NUXT_PUBLIC_SUPABASE_URL,
      supabaseKey: process.env.NUXT_PUBLIC_SUPABASE_KEY,
    },
  },
})
