-- * Shop personalization — Footspot-managed club shop config + per-product
-- * discounts. Counterpart: SHOP_PERSONALIZATION_GUIDE.md (Phase 1).
-- *
-- * Rule from the guide: never alter existing columns, only additions.
-- * clubs.slogan + clubs.accent_color already exist (20260423000001_club_branding).

-- * ── 1.1 clubs: shop-config audit trail + shop on/off status ──
DO $$ BEGIN
  CREATE TYPE club_shop_status AS ENUM ('active', 'disconnected');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE public.clubs
  -- * Bumped on any write through update-shop-config.
  ADD COLUMN IF NOT EXISTS shop_config_updated_at timestamptz,
  -- * "footspot" | "intersport_admin" — for v1 Footspot writes are "footspot".
  ADD COLUMN IF NOT EXISTS shop_config_updated_via text
    CHECK (shop_config_updated_via IS NULL
           OR shop_config_updated_via IN ('footspot', 'intersport_admin')),
  -- * 'disconnected' = director unpaired the shop; new checkouts are refused.
  ADD COLUMN IF NOT EXISTS shop_status club_shop_status NOT NULL DEFAULT 'active';

-- * ── 1.2 product_discounts — one row per (club, product_reference) ──
-- * discount_pct = 0 rows are kept as an audit trail of a cleared discount.
-- * Hard cap at 80 % matches Footspot's own check.
CREATE TABLE IF NOT EXISTS public.product_discounts (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id           uuid NOT NULL REFERENCES public.clubs(id) ON DELETE CASCADE,
  product_reference text NOT NULL,                            -- * matches products.reference
  discount_pct      smallint NOT NULL CHECK (discount_pct BETWEEN 0 AND 80),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  updated_via       text NOT NULL DEFAULT 'footspot'          -- * always 'footspot' in v1
                    CHECK (updated_via IN ('footspot', 'intersport_admin')),

  UNIQUE (club_id, product_reference)
);

-- * Partial index — the shop page only ever queries active (>0) discounts.
CREATE INDEX IF NOT EXISTS product_discounts_club_idx
  ON public.product_discounts(club_id)
  WHERE discount_pct > 0;

-- * RLS — public SELECT (the shop page renders discounts client-side); every
-- * write goes through service-role edge functions. Matches the SELECT-only
-- * policy pattern of sports/clubs/products (20260419000004_rls_policies.sql).
ALTER TABLE public.product_discounts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "public product_discounts" ON public.product_discounts;
CREATE POLICY "public product_discounts"
  ON public.product_discounts FOR SELECT USING (true);

-- * Data API grants (CLAUDE.md rule for every new public-schema table).
GRANT SELECT ON public.product_discounts TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.product_discounts TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.product_discounts TO service_role;

-- * ── 1.3 order_items: snapshot the club discount applied at order time ──
-- * The order is locked — later product_discounts changes never affect a
-- * placed order. unit_price_paid / fund_credit_snapshot already store the
-- * post-discount figures; this column records the % for receipts + Footspot.
ALTER TABLE public.order_items
  ADD COLUMN IF NOT EXISTS footspot_discount_pct smallint NOT NULL DEFAULT 0
    CHECK (footspot_discount_pct BETWEEN 0 AND 80);
